server:
  port: 8097

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: student-service
    

  
management:
  security:
    enabled: false

logging:
  level:
    com.example.howtodoinjava: DEBUG
    

spring:
  datasource:
    password: 
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2/testdb
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2_console
      enabled: true
